sudo: required
dist: trusty
language: node_js

node_js:
  - '10'

branches:
  only:
    - oas/testing
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - npm ci

before_script:
  - npm run check-package
  - npm run lint
  - npm run oas:generate

deploy:
  skip_cleanup: true
  provider: script
  script: bash bin/deploy.sh
  on:
    repo: thephez/dapi
    tags: true
