sudo: required
dist: trusty
language: node_js

node_js:
  - '10'

#branches:
#  only:
#    - oas/testing

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - npm ci

before_script:
  - npm run check-package
  - npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: bash bin/deploy.sh
  on:
    repo: thephez/dapi
    branch: oas/testing

after_success:
  - .travis/push.sh
