sudo: required
dist: trusty
language: node_js

node_js:
  - '8'
  - '10'

#branches:
  #only:
    #- master
    #- /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - npm ci

before_script:
  - npm run check-package
  - npm run lint

deploy:
  - provider: script
    skip_cleanup: true
    script: bash bin/deploy.sh
    on:
      repo: dashevo/dapi
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash bin/deploy-oas.sh
    on:
      repo: thephez/dapi
      all_branches: true
